jobs:
- job: 'Ubuntu_1604'
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: src/python-script/templates/python-script-steps.yml

- job: 'Ubuntu_1804'
  pool:
    vmImage: ubuntu-18.04
  steps:
  - template: src/python-script/templates/python-script-steps.yml

- job: 'Ubuntu_2004'
  pool:
    vmImage: ubuntu-20.04
  steps:
  - template: src/python-script/templates/python-script-steps.yml

- job: 'VS2017_Win2016'
  pool:
    vmImage: vs2017-win2016
  steps:
  - template: src/python-script/templates/python-script-steps.yml

- job: 'VS2019'
  pool:
    vmImage: windows-2019
  steps:
  - template: src/python-script/templates/python-script-steps.yml

- job: 'MacOS_Public_Mojave'
  pool:
    vmImage: macos-10.14
  steps:
  - template: src/python-script/templates/python-script-steps.yml

- job: 'MacOS_Public_Catalina'
  pool:
    vmImage: macos-10.15
  steps:
  - template: src/python-script/templates/python-script-steps.yml

# - job: 'MacOS_Public_BigSur'
#   pool:
#     vmImage: macos-11.0
#   steps:
#   - template: src/python-script/templates/python-script-steps.yml
